language: java
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
sudo: required
services:
- docker
notifications:
  email:
  - ludovic.piot@soat.fr
  on_success: always
  on_failure: always
branches:
  only:
  - master
env:
  global:
  - secure: IQcIxNgMk1ZIwA87n4untLTb9oZ9USWS7l1aVdhUqmGBSzTZE9DI88juWNr2+FQJGvqujHsPKlfcZIfQ9tnWO5xx+znMQYFqrctH5wCVqYwHsXYUB21IC0B2Jr6zu4CBRrZLh552ZgjScPaC/WekkDRhZjR1gXXRdLGYgtClGnazypROVwFlbzFrG7IHC/vqEktHkJkbpomfug8EPULd5s8vgUxVWKENBbKVu6MhZnlRCe7WDwhGCXjvIF+ldEo/chh5AHZ4kaSND63gf3h0xEcznMHxOscZCQ5kDCUipep6nKZWpZx3YlH3xY5d0ikxocJorFpKNQ3mh/BwjtlLkiWN7+sfmNdLqWP4pDkb4ojCcXuzAJv4ptdoNSU0P8vEIqrz9FSQWIndzTK5eXGZ5VTgTb2tCyLFTckYZwYu2Wej36L4uIopYZvD0Mhf7ttqz9MVVptm07eTe5b3yg3U7pwhBJZZV3NJEU/lxG12NaPxuM3xTu5a+6y91ez/CXYm+4lSmKP2Ht1z3aA5llPMqBVJD/CdCODl3DReR0/2ar4gLuabXdJIS2fx2UvGNOAhf13V53mpeAiLAt/qu8udMakJNY1ERkkLvHwXN5x87cp75d0zzdebcq8JVdWx1X4WrEc8fVZw9HN5PA/aeHYHU1F8Yhn510nFkTe0WkOqgG8=
  - secure: Rl6B+mKgj87rV854vuvXizE5d+sGU/dZpBq3t0WXCV5jmq/LsGYg7p15HCx3om85fTv+1zxV7PHYoqI/VVeIIkh+P2SW3Y6OJlKAXtCLy3N1Ud0jR+P/L1duPFp48g8sYgdwcO6du+pmO7Eso4j9IiKnJHB7OYPgTZnJmEx56LPNt1WiLY1AlW92FO61oz/7Qv0O9uouPL4L3LmybzGNpCxwvfHXlGwbW774HXiF0XZ7y/xbxntSKtmwnE1OnkqIxfzf5l5yHh/qEeHINwP+OfsmRwso9/qS8IVxCNsTyFPZX3HSwduT7rekErr/Wt9DnHYxlL+YWvNpUkk8zED0TiZdOqhXWwGwAi+hVIi1Es/rhgdsIe9TSs8LGPy2tO27syAQcvl0F/InkI58oNshFlGaaDMGFmx24F7aR3C/V7UBkHH7OaMF8jVhsVTAMtE34M4d18+0Igv6BY2YkAQF/BbfsVGLKAD9KEycD2jBSYmiTtKvy57eBPBLC60oGfrHb+Bl7Na2UB9+UX2148i2upm+PmOgVrdqQugfvWwFKKFBbusbecF4bnSfzRZKJvRApr5tYSGoHiQSaQBpwTPOlIrqB+UNi/5Y3mEodSP+WItHQndcqiScXSZRMKyZLRKiyY9D6d0bl91/dK/oXugrSx3uWV1kGWHDAkbtGwg9Vw0=
before_install:
- gem install travis -v 1.8.9 --no-document
- export BUILD_NAME=scc-confsvr-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh scripts/travis/tag_build.sh
- sh scripts/travis/build_services.sh
- sh scripts/travis/deploy_to_docker_hub.sh
